### ISSUE TITLE
embedding a corona wrapper?

### ISSUE THREAD

**Issue by khaelou** [CapsAdmin/goluwa#27]
Don't get me wrong Love is good, but it'll be great to see Corona support as well..

**Comment by CapsAdmin** [comment]
Maybe I will but why? I don't see the point for someone other than me. 

For me it's useful because it lets me test goluwa in ways I haven't before. It also makes me think about features I could add that I some mature framework like Corona has. But for anyone else I don't see the point, but I'm curious.
